# Generated by Django 3.2.10 on 2021-12-30 12:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('story_id', models.BigIntegerField(null=True)),
                ('type', models.CharField(max_length=200)),
                ('by', models.CharField(max_length=255)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('time', models.BigIntegerField(null=True)),
                ('text', models.TextField(null=True)),
                ('dead', models.BooleanField(default=False)),
                ('parent', models.BigIntegerField(null=True)),
                ('poll', models.BigIntegerField(null=True)),
                ('kids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(null=True), default=list, size=None)),
                ('url', models.URLField(null=True)),
                ('score', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('part', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(blank=True, null=True), default=list, size=None)),
                ('descendants', models.BigIntegerField(null=True)),
                ('is_hknews', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
    ]
