# Generated by Django 3.2.10 on 2021-12-30 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.TextField(null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
