# Generated by Django 3.2.10 on 2022-01-01 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='story_id',
            new_name='news_id',
        ),
    ]
