# Generated by Django 3.2.10 on 2022-01-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_comment_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_hknews',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.BigIntegerField(default=1641203181.413853, null=True),
        ),
    ]
